<?php

declare(strict_types=1);

use TYPO3\CMS\Extbase\Utility\ExtensionUtility;

ExtensionUtility::registerPlugin(
    'Forumman',
    'ForumForumlist',
    'LLL:EXT:forumman/Resources/Private/Language/locallang_db.xlf:plugin.forumlist.title',
    'ext-forumman-forumlist2',
    'Forum',
    'LLL:EXT:forumman/Resources/Private/Language/locallang_db.xlf:plugin.forumlist.description',
    'FILE:EXT:forumman/Configuration/FlexForms/Forum.xml'
);

ExtensionUtility::registerPlugin(
    'Forumman',
    'ForumForumuserlist',
    'LLL:EXT:forumman/Resources/Private/Language/locallang_db.xlf:plugin.forumlist.usertitle',
    'ext-forumman-userlist',
    'Forum',
    'LLL:EXT:forumman/Resources/Private/Language/locallang_db.xlf:plugin.forumlist.userdescription',
    'FILE:EXT:forumman/Configuration/FlexForms/Userlist.xml'
);

ExtensionUtility::registerPlugin(
    'Forumman',
    'ForumForumlogin',
    'LLL:EXT:forumman/Resources/Private/Language/locallang_db.xlf:plugin.forumlist.loginboxTitle',
    'ext-forumman-loginbox',
    'Forum',
    'LLL:EXT:forumman/Resources/Private/Language/locallang_db.xlf:plugin.forumlist.loginboxDescription',
);
ExtensionUtility::registerPlugin(
    'Forumman',
    'ForumForumregister',
    'LLL:EXT:forumman/Resources/Private/Language/locallang_db.xlf:plugin.forumlist.registerTitle',
    'content-webhook',
    'Forum',
    'LLL:EXT:forumman/Resources/Private/Language/locallang_db.xlf:plugin.forumlist.registerDescription',
    'FILE:EXT:forumman/Configuration/FlexForms/Register.xml'
);
ExtensionUtility::registerPlugin(
    'Forumman',
    'ForumForumWhoIsOnline',
    'LLL:EXT:forumman/Resources/Private/Language/locallang_db.xlf:plugin.forumlist.WhoisonlineTitle',
    'ext-forumman-whoisonline',
    'Forum',
    'LLL:EXT:forumman/Resources/Private/Language/locallang_db.xlf:plugin.forumlist.WhoisonlineDescription',
);
ExtensionUtility::registerPlugin(
    'Forumman',
    'ForumForumLastUsersOnline',
    'LLL:EXT:forumman/Resources/Private/Language/locallang_db.xlf:plugin.forumlist.LastuseronlineTitle',
    'ext-forumman-lastonline',
    'Forum',
    'LLL:EXT:forumman/Resources/Private/Language/locallang_db.xlf:plugin.forumlist.LastuseronlineDescription',
);
ExtensionUtility::registerPlugin(
    'Forumman',
    'ForumForumNewUser',
    'LLL:EXT:forumman/Resources/Private/Language/locallang_db.xlf:plugin.forumlist.NewusersTitle',
    'apps-pagetree-folder-contains-fe_users',
    'Forum',
    'LLL:EXT:forumman/Resources/Private/Language/locallang_db.xlf:plugin.forumlist.NewusersDescription',
);
ExtensionUtility::registerPlugin(
    'Forumman',
    'ForumForumStats',
    'LLL:EXT:forumman/Resources/Private/Language/locallang_db.xlf:plugin.forumlist.StatisticTitle',
    'ext-forumman-statistic',
    'Forum',
    'LLL:EXT:forumman/Resources/Private/Language/locallang_db.xlf:plugin.forumlist.StatisticDescription',
    'FILE:EXT:forumman/Configuration/FlexForms/Statistics.xml'
);
ExtensionUtility::registerPlugin(
    'Forumman',
    'ForumForumSearch',
    'LLL:EXT:forumman/Resources/Private/Language/locallang_db.xlf:plugin.forumlist.ElasticsearchTitle',
    'ext-forumman-search',
    'Forum-Suche',
    'LLL:EXT:forumman/Resources/Private/Language/locallang_db.xlf:plugin.forumlist.ElasticsearchDescription',
);
