forumman:
  view:
    templateRootPath: 'EXT:forumman/Resources/Private/Templates/'
    partialRootPath: 'EXT:forumman/Resources/Private/Partials/'
    layoutRootPath: 'EXT:forumman/Resources/Private/Layouts/'